import { DuckEvent, DuckEventPayload } from '../lib/duckEvents';

// -- Themed general messages (shown on toggle / quack) --

const MOTIVATIONAL = [
  'I believe in you!',
  "You've got this!",
  'One commit at a time.',
  'Progress, not perfection.',
  'Every bug fixed is a victory.',
  'Ship it when it feels right.',
  "You're closer than you think.",
  'The tests will pass. Eventually.',
  'Future you will thank present you.',
  'Debugging builds character.',
  'Trust the process. And the compiler.',
  'Small steps, big impact.'
];

const SARCASTIC = [
  "It's always DNS.",
  'Works on my machine.',
  "It's not a bug, it's a feature.",
  'Have you tried turning it off and on again?',
  'Maybe the real bug was the friends we made along the way.',
  'Ah yes, the classic off-by-one error. Or is it off-by-two?',
  'git blame says it was you.',
  "404: Solution not found. Just kidding, you'll get it.",
  'Ah yes, undefined is not a function. Classic.',
  "I'm sure the tests pass locally.",
  'Looks like a skill issue.',
  'This is what Stack Overflow was made for.',
  "Surely this won't break prod.",
  'git push --force and pray.',
  'Ah, another meeting that could have been a Slack message.',
  'The deadline was yesterday. No pressure.'
];

const TECHNICAL = [
  'Did you check the logs?',
  'Maybe add a console.log?',
  'Did you clear the cache?',
  'Try deleting node_modules.',
  'Are you sure it compiled?',
  'Have you tried reading the error message?',
  "It's probably a race condition.",
  'Is it plugged in?',
  'Have you checked the network tab?',
  'Maybe it needs a type assertion.',
  'Sounds like a missing await.',
  'Is that dependency up to date?',
  'Try adding a .catch() to that promise.',
  'Check if it works in an incognito tab.',
  'Did you remember to save the file?',
  'Is the environment variable set?',
  'Have you tried a fresh git clone?',
  "Maybe it's a circular dependency.",
  'Check the types. Always check the types.'
];

const QUACKS = [
  'Quack.',
  'Quack quack quack.',
  "That's quackers!",
  '*supportive quacking*',
  'Rubber duck debugging, activate!',
  'Have you tried explaining it out loud?',
  '*listens intently*',
  '*nods in duck*',
  '*quacks thoughtfully*',
  '*tilts head*',
  'Tell me more about this bug...',
  '*floats beside you*',
  '*waddles encouragingly*',
  'Quack? Quack.',
  '*preens feathers while you think*',
  "I'm all ears. Well, I'm all beak.",
  '*splashes in your terminal*',
  'Go on, I quack — I mean, I listen.',
  '*adjusts tiny rubber duck glasses*'
];

export const DUCK_MESSAGES = [...MOTIVATIONAL, ...SARCASTIC, ...TECHNICAL, ...QUACKS];

// -- Context-aware reaction messages --
// Messages containing {field} are only used when the payload has that field.
// Plain strings are always available as fallbacks.

type ReactionEntry = string | { template: string; requires: (keyof DuckEventPayload)[] };

const REACTION_MESSAGES: Record<DuckEvent, ReactionEntry[]> = {
  'pr:merged': [
    'Quack! It shipped!',
    'Merged! Time to celebrate.',
    'To production we go!',
    'Another one bites the dust.',
    'Merge commit secured.',
    '*celebratory quacking*',
    'The green button has been pressed!',
    'One less branch in the world.',
    '*does a little victory waddle*',
    'And just like that, it was done.',
    'git branch -d, you served us well.',
    'Main just got a little better.',
    '*throws confetti feathers*',
    "That's what I call a clean merge.",
    'The CI gods have smiled upon us.',
    'Deployed and unbothered.',
    { template: 'PR #{prNumber} merged! Ship it!', requires: ['prNumber'] },
    { template: '{prTitle} is live!', requires: ['prTitle'] },
    { template: 'PR #{prNumber} is now part of history.', requires: ['prNumber'] },
    { template: '#{prNumber} has entered the chat (and main).', requires: ['prNumber'] },
    { template: 'Farewell, #{prNumber}. You were a good branch.', requires: ['prNumber'] },
    { template: '"{prTitle}" — merged and deployed.', requires: ['prTitle'] },
    { template: '#{prNumber}: from draft to main. What a journey.', requires: ['prNumber'] },
    { template: "RIP #{prNumber}'s branch. Long live main.", requires: ['prNumber'] },
    { template: '"{prTitle}" is in the books.', requires: ['prTitle'] },
    { template: '#{prNumber} just graduated to production.', requires: ['prNumber'] }
  ],
  'pr:opened': [
    'A new PR! Exciting!',
    'Time for review!',
    'Fresh code incoming!',
    'PR opened! Now we wait...',
    "Let's hope CI passes.",
    '*optimistic quacking*',
    'Into the review queue it goes!',
    'Bold move. I like it.',
    'And so it begins...',
    '*quacks in anticipation*',
    'The diff looks great from here.',
    'Reviewers, assemble!',
    "Don't forget to self-review first.",
    'May your CI be green and your conflicts few.',
    '*refreshes PR page nervously*',
    'The hardest part is waiting for reviews.',
    { template: 'PR #{prNumber} is out there!', requires: ['prNumber'] },
    { template: '"{prTitle}" — sounds promising!', requires: ['prTitle'] },
    { template: '#{prNumber} is ready for eyeballs.', requires: ['prNumber'] },
    { template: '#{prNumber} just dropped. Reviews welcome.', requires: ['prNumber'] },
    { template: '"{prTitle}" — I would approve that.', requires: ['prTitle'] },
    { template: '#{prNumber} has entered the arena.', requires: ['prNumber'] },
    { template: '"{prTitle}" — the diff speaks for itself.', requires: ['prTitle'] },
    { template: "Good luck, #{prNumber}. You're gonna need it.", requires: ['prNumber'] },
    { template: '"{prTitle}": chapter one.', requires: ['prTitle'] },
    { template: "#{prNumber} is seeking approval. Aren't we all?", requires: ['prNumber'] }
  ],
  'pr:reviewed': [
    'Feedback time!',
    'Reviews are in!',
    '*attentive quacking*',
    'Someone looked at your code!',
    'The verdict is in...',
    'Review received. Deep breaths.',
    'A fresh pair of eyes!',
    '*peeks at the comments*',
    'Code review: the great equalizer.',
    'Opinions incoming!',
    'At least someone is reading your code.',
    '*braces for impact*',
    'Comments are just spicy suggestions.',
    'Time to read between the lines.',
    "Let's see what they think...",
    { template: '#{prNumber} has been reviewed!', requires: ['prNumber'] },
    { template: 'Someone has opinions about "{prTitle}".', requires: ['prTitle'] },
    { template: "#{prNumber} caught someone's attention.", requires: ['prNumber'] },
    { template: 'Eyes on "{prTitle}".', requires: ['prTitle'] },
    { template: '#{prNumber}: reviewed. The suspense builds.', requires: ['prNumber'] },
    { template: '"{prTitle}" is under the microscope.', requires: ['prTitle'] },
    { template: '#{prNumber} got some feedback. Brace yourself.', requires: ['prNumber'] }
  ],
  'pr:approved': [
    'Approved!',
    'LGTM!',
    'Ship it!',
    'Green across the board!',
    '*excited quacking*',
    'The stamp of approval!',
    'You earned that checkmark.',
    '*quacks with pride*',
    'Merge when ready, captain.',
    'No notes. Literally.',
    "They couldn't find a single nit. Impressive.",
    '*standing ovation quacking*',
    'The approver has spoken.',
    'All systems go.',
    'Permission to merge, granted.',
    'Clean code wins again.',
    { template: 'PR #{prNumber} approved!', requires: ['prNumber'] },
    { template: '#{prNumber} got the green light!', requires: ['prNumber'] },
    { template: '"{prTitle}" has been blessed.', requires: ['prTitle'] },
    { template: '#{prNumber}: approved. Go time.', requires: ['prNumber'] },
    { template: '"{prTitle}" passed the vibe check.', requires: ['prTitle'] },
    { template: '#{prNumber} is merge-ready. Your move.', requires: ['prNumber'] },
    { template: '"{prTitle}": approved. No objections.', requires: ['prTitle'] },
    { template: '#{prNumber} cleared for takeoff.', requires: ['prNumber'] },
    { template: '#{prNumber}: zero nits. A rare achievement.', requires: ['prNumber'] }
  ],
  'pr:changes-requested': [
    'Some changes needed...',
    'Back to the drawing board!',
    'Iterate iterate!',
    'Feedback is a gift. A slightly annoying gift.',
    'Almost there. Almost.',
    '*encouraging quack*',
    "It's not a rejection, it's a suggestion.",
    'Round two. Ding ding!',
    '*passes you a tissue*',
    "They're just nits. Probably.",
    "You'll get 'em next push.",
    'Every great PR has a revision arc.',
    "They're helping you write better code. That's the story.",
    '*quacks supportively*',
    "Nothing a force push can't fix. (Don't actually.)",
    'The best code is rewritten code. Or something.',
    'Take a breath. Then address the comments.',
    { template: 'PR #{prNumber} needs some love.', requires: ['prNumber'] },
    { template: '#{prNumber} is almost there — just a few tweaks.', requires: ['prNumber'] },
    { template: '"{prTitle}" needs another pass.', requires: ['prTitle'] },
    { template: '#{prNumber}: so close, yet so far.', requires: ['prNumber'] },
    { template: '#{prNumber} got sent back. It happens to the best of us.', requires: ['prNumber'] },
    { template: '"{prTitle}" has notes. Address them and come back stronger.', requires: ['prTitle'] },
    { template: '#{prNumber}: revision requested. You know the drill.', requires: ['prNumber'] },
    { template: '"{prTitle}" — round two incoming.', requires: ['prTitle'] },
    { template: '#{prNumber} will be even better after this.', requires: ['prNumber'] }
  ],
  error: [
    'Uh oh...',
    'There there...',
    '*concerned quacking*',
    'Quack... not good.',
    "Errors happen. That's what undo is for.",
    'Have you tried quacking at it?',
    "It's fine. Everything's fine.",
    '*pats you with wing*',
    'This too shall pass.',
    "Even senior devs get errors. It's fine.",
    '*hides behind your monitor*',
    'That was... unexpected.',
    "The stack trace knows what happened. You'll figure it out.",
    'If at first you fail, try try again.',
    '*nervous quacking*',
    'Look on the bright side: at least it failed loudly.',
    "I've seen worse. I think.",
    'Error is just another word for learning opportunity.',
    '*puts on hard hat*',
    "That's a feature request from the error gods.",
    'Have you considered that maybe the error is right?',
    'Errors are just the code being honest with you.',
    '*offers you a rubber duck*',
    'At least it errored before production. ...Right?'
  ],
  'jira:transition': [
    'Ticket moving!',
    'Progress!',
    'Workflow in motion!',
    'Status updated!',
    '*productive quacking*',
    'The board looks better already.',
    'Kanban dreams coming true.',
    '*drags ticket across the board*',
    'One column closer to done.',
    'The sprint board thanks you.',
    'Velocity: increasing.',
    'Your scrum master would be proud.',
    '*updates the burndown chart mentally*',
    'Flow state: achieved.',
    'The backlog trembles.',
    { template: '{ticketKey} → {status}!', requires: ['ticketKey', 'status'] },
    { template: '{ticketKey} is moving along!', requires: ['ticketKey'] },
    { template: '{ticketKey} leveled up to {status}.', requires: ['ticketKey', 'status'] },
    { template: '{ticketKey} has places to be.', requires: ['ticketKey'] },
    { template: '{ticketKey}: {status}. Onward!', requires: ['ticketKey', 'status'] },
    { template: '{ticketKey} just moved to {status}. Progress!', requires: ['ticketKey', 'status'] },
    { template: '{ticketKey} is now {status}. The board rejoices.', requires: ['ticketKey', 'status'] },
    { template: '{ticketKey}: status updated. Your standup just got easier.', requires: ['ticketKey'] },
    { template: '{ticketKey} changed lanes to {status}.', requires: ['ticketKey', 'status'] },
    { template: '{ticketKey} is on the move!', requires: ['ticketKey'] }
  ],
  'jira:linked': [
    'Ticket linked!',
    'Jira connection made!',
    'Tracking enabled!',
    'Code meets ticket!',
    'Traceability achieved.',
    '*organized quacking*',
    'Branch and ticket, sitting in a tree.',
    'Connected the dots!',
    '*files everything neatly*',
    'Your PM will be proud.',
    'Context: preserved.',
    'Now you can prove you did the work.',
    'Audit trail established.',
    'The code has a story now.',
    { template: '{ticketKey} linked to this branch!', requires: ['ticketKey'] },
    { template: '{ticketKey} now has a home.', requires: ['ticketKey'] },
    { template: '{ticketKey} and this branch are besties now.', requires: ['ticketKey'] },
    { template: '{ticketKey}: tracked and accounted for.', requires: ['ticketKey'] },
    { template: '{ticketKey} is now part of the story.', requires: ['ticketKey'] },
    { template: '{ticketKey} linked. Your commits have meaning now.', requires: ['ticketKey'] },
    { template: '{ticketKey}: connected. No more mystery commits.', requires: ['ticketKey'] }
  ],
  'jira:configured': [
    'Jira ready!',
    'Integration complete!',
    'Connected to Jira!',
    'The pipeline is flowing!',
    '*impressed quacking*',
    'Jira and terminal, together at last.',
    'Setup complete. Time to be productive.',
    '*quacks approvingly*',
    'The tools are connected. The workflow is whole.',
    'Now the real fun begins.',
    'Terminal + Jira = unstoppable.',
    'One less browser tab needed.',
    'You just leveled up your workflow.',
    '*nods in DevOps*'
  ],
  'jira:assigned': [
    'Assigned!',
    'On it!',
    'Claimed!',
    "It's yours now!",
    '*dutiful quacking*',
    'Ownership established.',
    'Responsibility accepted.',
    '*salutes*',
    'A ticket has found its champion.',
    'Challenge accepted.',
    'With great tickets comes great responsibility.',
    'The chosen one.',
    '*pins ticket to your desk*',
    "It's dangerous to go alone — take this ticket.",
    { template: '{ticketKey} assigned to {assignee}!', requires: ['ticketKey', 'assignee'] },
    { template: '{ticketKey} has an owner now!', requires: ['ticketKey'] },
    { template: '{assignee} is on the case!', requires: ['assignee'] },
    { template: '{assignee} accepted the quest: {ticketKey}.', requires: ['ticketKey', 'assignee'] },
    { template: '{ticketKey} found its person.', requires: ['ticketKey'] },
    { template: '{assignee} picked up {ticketKey}. Bold.', requires: ['ticketKey', 'assignee'] },
    { template: '{ticketKey} → {assignee}. Good luck!', requires: ['ticketKey', 'assignee'] },
    { template: '{assignee} volunteered as tribute for {ticketKey}.', requires: ['ticketKey', 'assignee'] },
    { template: "{ticketKey} is in {assignee}'s hands now.", requires: ['ticketKey', 'assignee'] },
    { template: '{assignee}: you own {ticketKey}. No takebacks.', requires: ['ticketKey', 'assignee'] }
  ],
  'jira:unassigned': [
    'Unassigned!',
    'Free agent!',
    'Released!',
    'Back to the pool.',
    '*liberated quacking*',
    'Ticket is up for grabs.',
    'Back to the backlog wilderness.',
    '*waves goodbye*',
    'An orphan ticket in the wild.',
    'Someone will pick it up. Probably.',
    'Into the void it goes.',
    'Not my ticket, not my problem.',
    '*whistles innocently*',
    'Free as a bird. Well, a duck.',
    { template: '{ticketKey} is unassigned.', requires: ['ticketKey'] },
    { template: '{ticketKey} needs a new hero.', requires: ['ticketKey'] },
    { template: '{ticketKey} is looking for a volunteer.', requires: ['ticketKey'] },
    { template: 'Who wants {ticketKey}? Anyone?', requires: ['ticketKey'] },
    { template: '{ticketKey} has been released into the wild.', requires: ['ticketKey'] },
    { template: '{ticketKey}: abandoned. *sad quack*', requires: ['ticketKey'] },
    { template: '{ticketKey} is available. First come, first served.', requires: ['ticketKey'] },
    { template: '{ticketKey} is free. Like a duck on a pond.', requires: ['ticketKey'] }
  ]
};

function fillTemplate(template: string, payload: DuckEventPayload): string {
  return template.replace(/\{(\w+)\}/g, (_, key) => {
    const val = payload[key as keyof DuckEventPayload];
    return val !== undefined ? String(val) : `{${key}}`;
  });
}

export function pickReactionMessage(event: DuckEvent, payload?: DuckEventPayload): string {
  const entries = REACTION_MESSAGES[event];

  // Build candidate list: resolve templates if payload satisfies requirements
  const candidates: string[] = [];
  for (const entry of entries) {
    if (typeof entry === 'string') {
      candidates.push(entry);
    } else if (payload && entry.requires.every((k) => payload[k] !== undefined)) {
      candidates.push(fillTemplate(entry.template, payload));
    }
  }

  return candidates[Math.floor(Math.random() * candidates.length)]!;
}
